<?php
/**
 * @var Payone_Core_Block_Checkout_Onepage_Review_SepaMandate $this
 */
?>

<?php if ($this->showMandate()): ?>
    <div style="border: 1px solid #d9dde3; border-width: 0 1px;">
        <div class="mandate">
            <?php echo $this->getMandateTextDecoded(); ?>
        </div>
        <br/>
        <label style="margin-left: 30px;">
            <input type="checkbox" id="payone_sepa_mandate_accept" name="payone[sepa_mandate_accept]"
                   onchange="changeSubmitButtonStatus(this);" value="payone_sepa_mandate_accept">
            <?php echo $this->__("I want to grant the mandate (transmitted electronically)"); ?>
        </label>
    </div>

    <script type="text/javascript">
        $$('.btn-checkout')[0].setAttribute("disabled", "disabled");
        $$('.btn-checkout')[0].hide();
    </script>
<?php endif; ?>