<!--@subject Please update your payment information @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Valued customer,<br><br>

    Thank you very much for your order at {{var store.getFrontendName()}}.<br><br>

    Amazon Pay was not able to process your payment.
    Please go to <a href="https://pay.amazon.com/uk/jr/your-account/orders?language=en_GB">https://pay.amazon.com/uk/jr/your-account/orders?language=en_GB</a> and update the payment information for your order. Afterwards we will automatically request payment again from Amazon Pay and you will receive a confirmation email.<br><br>

    Kind regards,<br><br>

    {{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
