<!--@subject Processing error of PAYONE payment status messages @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Dear Sir or Madam,<br>
    <br>
    The following PAYONE payment status messages were not processed correctly:<br>
    {{var failedTxIds}}<br>
    <br>
    You can find more detailed error information in the database table payone_protocol_transactionstatus.<br>
    Use the following SQL command to display the incorrect payment status messages.<br>
    <br>
<pre>SELECT * FROM `payone_protocol_transactionstatus` WHERE `id` IN
    ({{var failedIds}});</pre>
<br>
With kind regards<br>
{{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
