<?php
/**
 * @var Payone_Core_Block_PaymentAdditionalStyle $this
 */
?>
<?php
    foreach ($this->getActiveShortcuts() as $url) {
        echo '<link rel="stylesheet" href="' . $url  . '" />' . PHP_EOL;
    }

    $ratepayExternalStyleUrl = $this->getRatepayExternalStyleUrl();
    if (!empty($ratepayExternalStyleUrl)) {
        echo '<link rel="stylesheet" href="' . $ratepayExternalStyleUrl  . '" />' . PHP_EOL;
    }
?>
