<!--@subject Bitte kontaktieren Sie uns wegen Ihrer Bestellung @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Sehr geehrter Kunde,<br><br>

    Leider wurde die Zahlung zu Ihrer Bestellung in unserem Onlineshop {{var store.getFrontendName()}} von Amazon Pay zurückgewiesen.<br>
    Bitte kontaktieren Sie uns.<br><br>

    Mit freundlichen Grüßen<br><br>

    {{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
