<!--@subject Bitte aktualisieren Sie Ihre Zahlungsinformationen @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Sehr geehrter Kunde,<br><br>

    Vielen Dank für Ihre Bestellung bei {{var store.getFrontendName()}}.<br><br>

    Leider wurde Ihre Bezahlung von Amazon Pay abgelehnt.<br>
    Sie können unter <a href="https://pay.amazon.com/de/jr/your-account/orders?language=de_DE">https://pay.amazon.com/de/jr/your-account/orders?language=de_DE</a> die Zahlungsinformationen für Ihre Bestellung aktualisieren, indem Sie eine andere Zahlungsweise auswählen oder eine neue Zahlungsweise angeben. Mit der neuen Zahlungsweise wird dann ein erneuter Zahlungsversuch vorgenommen, und Sie erhalten eine Bestätigungsemail.<br><br>

    Mit freundlichen Grüßen<br><br>

    {{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
