<!--@subject Transactions status error report @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Sehr geehrte Damen und Herren,<br><br>

    Folgende Transaktionen wurden nicht ordnungsgemäß verarbeitet:
    {{ var failedIds }}
    <br>
    <br>
    Mit freundlichen Grüßen<br>
    {{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
