<!--@subject Verarbeitungsfehler von PAYONE Zahlstatusmeldungen @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Sehr geehrte Damen und Herren,<br>
    <br>
    Folgende PAYONE Zahlstatusmeldungen wurden nicht ordnungsgemäß verarbeitet:<br>
    {{var failedTxIds}}<br>
    <br>
    Sie finden weiterführende Fehlerinformationen in der Datenbanktabelle payone_protocol_transactionstatus.<br>
    Nutzen Sie den folgenden SQL Befehl, um die fehlerhaften Zahlstatusmeldungen anzuzeigen.<br>
    <br>
    <pre>SELECT * FROM `payone_protocol_transactionstatus` WHERE `id` IN
    ({{var failedIds}});</pre>
    <br>
    Mit freundlichen Grüßen<br>
    {{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
