<!--@subject Transactions status error report @-->
<!--@vars
{"store url=\"\"":"Store Url",
"var logo_url":"Email Logo Image Url",
"var logo_alt":"Email Logo Image Alt",
"var store.getFrontendName()":"Store Name",
@-->
<!--@styles
@-->

{{template config_path="design/email/header"}}
{{inlinecss file="email-inline.css"}}

<p>
    Sehr geehrter Damen und Herren,<br><br>

    Folgende Folgende Transactionen könnten nicht bearbeitet werden:
    {{var transactionsList }}

    Mit freundlichen Grüßen<br><br>

    {{var store.getFrontendName()}}
</p>

{{template config_path="design/email/footer"}}
