<?php if ($this->displayPrompt() === true) : ?>
<div id="overlay"></div>
<div id="cancellation-confirmation-box">
    <p style="font-weight: bold">
        <?php
            echo $this->helper('payone_core')->__('Note. The money could not be refunded.');
        ?>
    </p>
    <p>
        <?php
            $text = $this->helper('payone_core')->__('You can cancel the order in the shop, but the transaction have to be manually cancelled in the Payone Merchant Interface.');
            $text = preg_replace('/Payone Merchant Interface/', $this->helper('payone_core')->getPmiLink(), $text);
            echo $text;
        ?>
    </p>
    <br />
    <p>
        <?php
            echo $this->helper('payone_core')->__('Do you want to cancel the order in the shop ?');
        ?>
    </p>
    <p style="text-align: right">
        <button class="scalable back" onclick="setLocation('<?php echo $this->getOrderViewUrl(); ?>')"><?php echo $this->helper('payone_core')->__('No'); ?></button>
        <button onclick="setLocation('<?php echo $this->getCancelUrl(); ?>')"><?php echo $this->helper('payone_core')->__('Yes'); ?></button>
    </p>
</div>
<style>
    #overlay {
        position: fixed;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0,0,0,0.5);
        z-index: 100;
    }
    #cancellation-confirmation-box {
        position: fixed;
        width: 40%;
        top: 30%;
        left: 30%;
        padding: 15px 15px 10px;
        border: solid 2px black;
        background-color: rgb(255,240,240);
        z-index: 101;
    }
</style>
<?php endif ?>